version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/project
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/awsbeginer-bucket-deploy
    owner: root
    group: root
    mode: 775

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
