version: 0.0
os: linux
# source 가 현재 경로에 있으면  /home/ec2-user/project  경로에 압축 풀기를 실시합니다.
  - source: /  # 현재 경로에 있는 소스
    destination: /home/ec2-user/project  # 이 경로로 복사 합니다.
    overwrite: yes

hooks:
  AfterInstall: 
    - location: scripts/deploy.sh
      timeout: 300
      runas: root