# 액션 이름
name: Test Action

# 이벤트 등록
on:
  # 풀 리퀘스트 시
  pull_request:
    branches:
      - main
      - dev

  # push 시
  push:
    branches:
      - main
      - dev

# 실행할 작업들
jobs:
  test:
    runs-on: ubuntu-latest # 작업의 실행환경을 최근 버전의 우분투로
    steps:
      - uses: actions/checkout@v4

      - name: Set up NodeJS # 노드 설치
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0 # 현재 노드 버전

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
